controller:
  image:
    registry: docker.io
    repository: rushii01/jenkins-k8s
    tag: "1.0"
    pullPolicy: IfNotPresent

  serviceType: NodePort
  servicePort: 8080
  nodePort: 32000

  serviceAccount:
    create: true
    name: jenkins

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - docker-workflow
    - git
    - configuration-as-code

  extraVolumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock

  extraVolumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

  persistence:
      enabled: false

